import { useState } from 'react';
import { Download, Printer } from 'lucide-react';
import type { Component, GradeResult } from '../lib/calculationEngine';
import { percentToGPA, formatGPA } from '../lib/gpaScale';

interface Props {
  components: Component[];
  gradeResult: GradeResult | null;
  target: number;
  subjectName?: string;
}

export default function ExportButton({ components, gradeResult, target, subjectName }: Props) {
  const [open, setOpen] = useState(false);

  const handlePrint = () => {
    const totalEntries = components.reduce((s, c) => s + c.entries.length, 0);
    if (!gradeResult || totalEntries === 0) return;

    const gpa = percentToGPA(gradeResult.currentGrade);
    const gpaLabel = gpa <= 1.25 ? "Dean's List" : gpa <= 1.75 ? 'Very Good' : gpa <= 2.50 ? 'Good' : gpa <= 3.00 ? 'Passing' : 'Below Passing';
    const date = new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });
    const totalWeight = components.reduce((s, c) => s + c.weight, 0);

    const rows = components.map(comp => {
      const avg = gradeResult.componentAverages.get(comp.id) ?? -1;
      const entries = comp.entries.map(e => `${e.label || 'Entry'}: ${e.score}/${e.max_score}`).join(', ');
      return `
        <tr>
          <td>${comp.name}</td>
          <td>${comp.weight}%</td>
          <td>${avg >= 0 ? avg.toFixed(2) + '%' : '—'}</td>
          <td style="font-size:11px;color:#666">${entries || '—'}</td>
          <td>${comp.done ? '✓ Done' : 'In Progress'}</td>
        </tr>
      `;
    }).join('');

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>AcadNest Grade Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #111; background: white; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; border-bottom: 2px solid #FFD45A; padding-bottom: 20px; }
    .brand { font-size: 22px; font-weight: 800; color: #1a1a1a; }
    .brand span { color: #b8860b; }
    .meta { text-align: right; font-size: 12px; color: #666; }
    .grade-hero { display: flex; gap: 32px; margin-bottom: 28px; }
    .stat-box { background: #f8f8f8; border-radius: 12px; padding: 20px 28px; min-width: 160px; }
    .stat-label { font-size: 10px; color: #999; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }
    .stat-value { font-size: 32px; font-weight: 900; }
    .stat-sub { font-size: 11px; color: #888; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { text-align: left; font-size: 10px; color: #999; text-transform: uppercase; letter-spacing: 0.5px; padding: 8px 12px; border-bottom: 1px solid #eee; }
    td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; font-size: 13px; vertical-align: top; }
    tr:last-child td { border-bottom: none; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; font-size: 10px; color: #bbb; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">Acad<span>Nest</span></div>
      <div style="font-size:13px;color:#888;margin-top:4px">Grade Report</div>
      ${subjectName ? `<div style="font-size:16px;font-weight:700;margin-top:8px">${subjectName}</div>` : ''}
    </div>
    <div class="meta">
      <div>${date}</div>
      <div style="margin-top:4px">Target: ${target}%</div>
      <div style="margin-top:2px">${totalWeight}% total weight</div>
    </div>
  </div>

  <div class="grade-hero">
    <div class="stat-box">
      <div class="stat-label">Current Grade</div>
      <div class="stat-value" style="color:#b8860b">${gradeResult.currentGrade.toFixed(2)}%</div>
      <div class="stat-sub">${gpaLabel}</div>
    </div>
    <div class="stat-box">
      <div class="stat-label">GPA Equivalent</div>
      <div class="stat-value">${formatGPA(gpa)}</div>
      <div class="stat-sub">Philippine 1.0–5.0 scale</div>
    </div>
    <div class="stat-box">
      <div class="stat-label">Max Possible</div>
      <div class="stat-value" style="color:#22c55e">${gradeResult.maxPossibleGrade.toFixed(2)}%</div>
      <div class="stat-sub">${gradeResult.isComplete ? 'Final grade' : 'If all remaining = 100%'}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Component</th>
        <th>Weight</th>
        <th>Average</th>
        <th>Entries</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    Generated by AcadNest · Free grade tracking for Philippine university students
  </div>
</body>
</html>`;

    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.onload = () => win.print();
    setOpen(false);
  };

  if (!gradeResult) return null;

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl themed-surface hover:themed-surface-h border themed-border themed-text/35 hover:themed-text/55 text-[11px] transition-colors cursor-pointer"
      >
        <Download className="w-3.5 h-3.5" />
        Export
      </button>
      {open && (
        <>
          <div className="fixed inset-0 z-30" onClick={() => setOpen(false)} />
          <div className="absolute right-0 top-full mt-1 w-44 rounded-xl bg-[#12121f] border themed-border-subtle shadow-2xl z-40 overflow-hidden">
            <button
              onClick={handlePrint}
              className="w-full flex items-center gap-2.5 px-4 py-3 text-[12px] themed-text/60 hover:themed-surface-h hover:themed-text/80 transition-colors cursor-pointer text-left"
            >
              <Printer className="w-3.5 h-3.5" />
              Print / Save PDF
            </button>
            <div className="px-4 py-2 text-[10px] themed-text/20 border-t themed-border">
              Opens print dialog
            </div>
          </div>
        </>
      )}
    </div>
  );
}
